# Generated by Django 6.0.1 on 2026-01-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Interest', 'Interest'), ('Fee', 'Fee')], default='DEPOSIT'),
            preserve_default=False,
        ),
    ]
